# CMake generated Testfile for 
# Source directory: D:/Gitrep/test_task/sourcescsvp
# Build directory: D:/Gitrep/test_task/tempcsvp
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Usage1 "D:/Gitrep/test_task/tempcsvp/Debug/csvp.exe")
  set_tests_properties(Usage1 PROPERTIES  PASS_REGULAR_EXPRESSION "Usage: .* .* .*" _BACKTRACE_TRIPLES "D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;32;add_test;D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Usage1 "D:/Gitrep/test_task/tempcsvp/Release/csvp.exe")
  set_tests_properties(Usage1 PROPERTIES  PASS_REGULAR_EXPRESSION "Usage: .* .* .*" _BACKTRACE_TRIPLES "D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;32;add_test;D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Usage1 "D:/Gitrep/test_task/tempcsvp/MinSizeRel/csvp.exe")
  set_tests_properties(Usage1 PROPERTIES  PASS_REGULAR_EXPRESSION "Usage: .* .* .*" _BACKTRACE_TRIPLES "D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;32;add_test;D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Usage1 "D:/Gitrep/test_task/tempcsvp/RelWithDebInfo/csvp.exe")
  set_tests_properties(Usage1 PROPERTIES  PASS_REGULAR_EXPRESSION "Usage: .* .* .*" _BACKTRACE_TRIPLES "D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;32;add_test;D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;0;")
else()
  add_test(Usage1 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Empfile "D:/Gitrep/test_task/tempcsvp/Debug/csvp.exe" "D:\\Gitrep\\test_task\\filesfortests\\globalinput0.json")
  set_tests_properties(Empfile PROPERTIES  PASS_REGULAR_EXPRESSION "File is empty." _BACKTRACE_TRIPLES "D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;36;add_test;D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Empfile "D:/Gitrep/test_task/tempcsvp/Release/csvp.exe" "D:\\Gitrep\\test_task\\filesfortests\\globalinput0.json")
  set_tests_properties(Empfile PROPERTIES  PASS_REGULAR_EXPRESSION "File is empty." _BACKTRACE_TRIPLES "D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;36;add_test;D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Empfile "D:/Gitrep/test_task/tempcsvp/MinSizeRel/csvp.exe" "D:\\Gitrep\\test_task\\filesfortests\\globalinput0.json")
  set_tests_properties(Empfile PROPERTIES  PASS_REGULAR_EXPRESSION "File is empty." _BACKTRACE_TRIPLES "D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;36;add_test;D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Empfile "D:/Gitrep/test_task/tempcsvp/RelWithDebInfo/csvp.exe" "D:\\Gitrep\\test_task\\filesfortests\\globalinput0.json")
  set_tests_properties(Empfile PROPERTIES  PASS_REGULAR_EXPRESSION "File is empty." _BACKTRACE_TRIPLES "D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;36;add_test;D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;0;")
else()
  add_test(Empfile NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Correctfile "D:/Gitrep/test_task/tempcsvp/Debug/csvp.exe" "D:\\Gitrep\\test_task\\filesfortests\\globalinput1.json")
  set_tests_properties(Correctfile PROPERTIES  PASS_REGULAR_EXPRESSION ".* No changes in file.*" _BACKTRACE_TRIPLES "D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;40;add_test;D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Correctfile "D:/Gitrep/test_task/tempcsvp/Release/csvp.exe" "D:\\Gitrep\\test_task\\filesfortests\\globalinput1.json")
  set_tests_properties(Correctfile PROPERTIES  PASS_REGULAR_EXPRESSION ".* No changes in file.*" _BACKTRACE_TRIPLES "D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;40;add_test;D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Correctfile "D:/Gitrep/test_task/tempcsvp/MinSizeRel/csvp.exe" "D:\\Gitrep\\test_task\\filesfortests\\globalinput1.json")
  set_tests_properties(Correctfile PROPERTIES  PASS_REGULAR_EXPRESSION ".* No changes in file.*" _BACKTRACE_TRIPLES "D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;40;add_test;D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Correctfile "D:/Gitrep/test_task/tempcsvp/RelWithDebInfo/csvp.exe" "D:\\Gitrep\\test_task\\filesfortests\\globalinput1.json")
  set_tests_properties(Correctfile PROPERTIES  PASS_REGULAR_EXPRESSION ".* No changes in file.*" _BACKTRACE_TRIPLES "D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;40;add_test;D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;0;")
else()
  add_test(Correctfile NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(CorrectEmpFile "D:/Gitrep/test_task/tempcsvp/Debug/csvp.exe" "D:\\Gitrep\\test_task\\filesfortests\\globalinput2.json")
  set_tests_properties(CorrectEmpFile PROPERTIES  PASS_REGULAR_EXPRESSION ".* No changes in file.*" _BACKTRACE_TRIPLES "D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;44;add_test;D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(CorrectEmpFile "D:/Gitrep/test_task/tempcsvp/Release/csvp.exe" "D:\\Gitrep\\test_task\\filesfortests\\globalinput2.json")
  set_tests_properties(CorrectEmpFile PROPERTIES  PASS_REGULAR_EXPRESSION ".* No changes in file.*" _BACKTRACE_TRIPLES "D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;44;add_test;D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(CorrectEmpFile "D:/Gitrep/test_task/tempcsvp/MinSizeRel/csvp.exe" "D:\\Gitrep\\test_task\\filesfortests\\globalinput2.json")
  set_tests_properties(CorrectEmpFile PROPERTIES  PASS_REGULAR_EXPRESSION ".* No changes in file.*" _BACKTRACE_TRIPLES "D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;44;add_test;D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(CorrectEmpFile "D:/Gitrep/test_task/tempcsvp/RelWithDebInfo/csvp.exe" "D:\\Gitrep\\test_task\\filesfortests\\globalinput2.json")
  set_tests_properties(CorrectEmpFile PROPERTIES  PASS_REGULAR_EXPRESSION ".* No changes in file.*" _BACKTRACE_TRIPLES "D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;44;add_test;D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;0;")
else()
  add_test(CorrectEmpFile NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(NotExistFile "D:/Gitrep/test_task/tempcsvp/Debug/csvp.exe" "D:\\Gitrep\\test_task\\filesfortests\\globalinput3.json")
  set_tests_properties(NotExistFile PROPERTIES  PASS_REGULAR_EXPRESSION "File .* does not exist." _BACKTRACE_TRIPLES "D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;48;add_test;D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(NotExistFile "D:/Gitrep/test_task/tempcsvp/Release/csvp.exe" "D:\\Gitrep\\test_task\\filesfortests\\globalinput3.json")
  set_tests_properties(NotExistFile PROPERTIES  PASS_REGULAR_EXPRESSION "File .* does not exist." _BACKTRACE_TRIPLES "D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;48;add_test;D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(NotExistFile "D:/Gitrep/test_task/tempcsvp/MinSizeRel/csvp.exe" "D:\\Gitrep\\test_task\\filesfortests\\globalinput3.json")
  set_tests_properties(NotExistFile PROPERTIES  PASS_REGULAR_EXPRESSION "File .* does not exist." _BACKTRACE_TRIPLES "D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;48;add_test;D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(NotExistFile "D:/Gitrep/test_task/tempcsvp/RelWithDebInfo/csvp.exe" "D:\\Gitrep\\test_task\\filesfortests\\globalinput3.json")
  set_tests_properties(NotExistFile PROPERTIES  PASS_REGULAR_EXPRESSION "File .* does not exist." _BACKTRACE_TRIPLES "D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;48;add_test;D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;0;")
else()
  add_test(NotExistFile NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(FileErrorInSum "D:/Gitrep/test_task/tempcsvp/Debug/csvp.exe" "D:\\Gitrep\\test_task\\filesfortests\\globalinput4.json")
  set_tests_properties(FileErrorInSum PROPERTIES  PASS_REGULAR_EXPRESSION ".* There are changes in file" _BACKTRACE_TRIPLES "D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;52;add_test;D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(FileErrorInSum "D:/Gitrep/test_task/tempcsvp/Release/csvp.exe" "D:\\Gitrep\\test_task\\filesfortests\\globalinput4.json")
  set_tests_properties(FileErrorInSum PROPERTIES  PASS_REGULAR_EXPRESSION ".* There are changes in file" _BACKTRACE_TRIPLES "D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;52;add_test;D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(FileErrorInSum "D:/Gitrep/test_task/tempcsvp/MinSizeRel/csvp.exe" "D:\\Gitrep\\test_task\\filesfortests\\globalinput4.json")
  set_tests_properties(FileErrorInSum PROPERTIES  PASS_REGULAR_EXPRESSION ".* There are changes in file" _BACKTRACE_TRIPLES "D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;52;add_test;D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(FileErrorInSum "D:/Gitrep/test_task/tempcsvp/RelWithDebInfo/csvp.exe" "D:\\Gitrep\\test_task\\filesfortests\\globalinput4.json")
  set_tests_properties(FileErrorInSum PROPERTIES  PASS_REGULAR_EXPRESSION ".* There are changes in file" _BACKTRACE_TRIPLES "D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;52;add_test;D:/Gitrep/test_task/sourcescsvp/CMakeLists.txt;0;")
else()
  add_test(FileErrorInSum NOT_AVAILABLE)
endif()
